### ISSUE TITLE
would you please add the navigation of the method usages?

### ISSUE THREAD

**Issue by CoinCheung** [tacahiroy/ctrlp-funky#104]
I appreciate your script allows the jump to the methods definition. However, I feel it would be equally useful to allow the users to see the positions where the current method is called and make a jump. Just like the way cscope does. Would you add this feature?

**Comment by timfeirg** [comment]
care to elaborate? not sure what you mean

**Comment by tacahiroy** [comment]
You can use `:CtrlPLine` or `*` to find positions the current method is called.

**Comment by tacahiroy** [comment]
No response. closing
