### ISSUE TITLE
funky show error

### ISSUE THREAD

**Issue by jacky1193610322** [tacahiroy/ctrlp-funky#109]
I enable the ale check when start vim, but if open ctrlp-funky to find python function, the quickfix show the flake8 error, I don't want check them.
I try to disable ale when bufenter, and enable ale when bufleave
but i found  BufLeave is be ignore in the source code. 

![image](https://user-images.githubusercontent.com/16514353/29917239-edd162ca-8e73-11e7-868d-1292be8fe452.png)
Thank you.

**Comment by tacahiroy** [comment]
I've checked Ale's help and found a way to achieve that.
You can disable check on Funky window by setting `b:ale_enabled` to 0:
```vim
autocmd BufEnter ControlP let b:ale_enabled = 0
```

**Comment by jacky1193610322** [comment]
yeah  it works, thank you very much.

**Comment by jacky1193610322** [comment]
i did't see the #109 sorry
