### ISSUE TITLE
ctrlp funky show ale error

### ISSUE THREAD

**Issue by jacky1193610322** [tacahiroy/ctrlp-funky#110]
I enable the ale check when start vim, but if open ctrlp-funky to find python function, the quickfix show the flake8 error, I don't want to check the quickfix.
![image](https://user-images.githubusercontent.com/16514353/29919920-cf765a7e-8e7d-11e7-87a4-7d40b5baedaa.png)

I try to enable ale when Bufenter and disbale ale when BufLeave
au BufEnter ControlP :ALEDisable
au BufLeave ControlP :ALEDEnable
but it doesn't work, i found it ignore BufLeave event in the source code,
how should i do?
Thank you

**Comment by tacahiroy** [comment]
have you tried the way I commented on #109?

**Comment by tacahiroy** [comment]
duplicated to #109. closing
