### ISSUE TITLE
ctrlp-funky  red color for space

### ISSUE THREAD

**Issue by jacky1193610322** [tacahiroy/ctrlp-funky#111]
![image](https://user-images.githubusercontent.com/16514353/29952238-c221d6fa-8efa-11e7-9fb7-8844f2297932.png)
Thank you for #110 , but there are some red color for space, ctrlp doesn't show it,
so I want to syntax on the result, but don't show the red block.
Thank you

**Comment by tacahiroy** [comment]
That's the limitation of the feature.
See https://github.com/tacahiroy/ctrlp-funky#syntax-highlighting.

**Comment by jacky1193610322** [comment]
But when I set g:ctrlp_funky_syntax_highlight = 0, it also doesn't work

**Comment by tacahiroy** [comment]
Can you check `g:ctrlp_funky_syntax_highlight = 0` with this branch: [topic/fix-highlight-setting-for-ctrlp-buffer](https://github.com/tacahiroy/ctrlp-funky/compare/topic/fix-highlight-setting-for-ctrlp-buffer)

**Comment by jacky1193610322** [comment]
it works, thank you

**Comment by tacahiroy** [comment]
cool - have merged it to master
