### ISSUE TITLE
Is it possible to go back to reference?

### ISSUE THREAD

**Issue by troyoung** [tacahiroy/ctrlp-funky#112]
Most of the times, when I use <leader>fU<CR> find and goto the definition of a function,  usually I want to go back to where I left just like ctrl-t in ctrlp.

**Comment by tacahiroy** [comment]
You can use a basic Vim function <C-o> to go back to the row where you
were. Is it enough?--

Takahiro Yoshihara
tacahiroy@gmail

**Comment by troyoung** [comment]
Wow, it works, thanks a lot
