### ISSUE TITLE
ctrlp-funky syntax highlight does not work anymore

### ISSUE THREAD

**Issue by cangermueller** [tacahiroy/ctrlp-funky#115]
Hi all,

ctrlp-funky syntax highlight does not work anymore after I updated to the latest version. Syntax highlight works in the main window, but not in the ctrlp-funky window. The problem is independent of the filetype, i.e. it does not work, e.g., for shell or python scripts.
Does someone have the same problem? Were there some recent changes related to syntax highlighting?

Thanks!

image
![image](https://user-images.githubusercontent.com/4807859/41504175-488eb44a-719c-11e8-8486-5500da14603d.png)

**Comment by tacahiroy** [comment]
This issued should be fixed by this PR: https://github.com/ctrlpvim/ctrlp.vim/pull/451
closing.
