### ISSUE TITLE
vim fold marker navigation

### ISSUE THREAD

**Issue by timfeirg** [tacahiroy/ctrlp-funky#119]
I personally use folds to organize my [`.vimrc`](https://github.com/timfeirg/workspace-setup/blob/master/.nvimrc):

```
" vim: set sw=4 ts=4 sts=4 et tw=78 foldmarker={,} foldlevel=0 foldmethod=marker:
```

This allows me to put configurations for different plugins in different sections:

```vimL
" ctrlp and plugins {
let g:ctrlp_mruf_case_sensitive = 0
" yankring {
let g:ctrlp_yankring_limit = 100
" }
" funky {
let g:ctrlp_funky_use_cache = 1
" }
" }
```

So naturally I want some sort of navigation between all these different fold block.

I tried so hard to compose a regex pattern for the fold marker, something like `^[\t ]*"[\t ]*.\+{`, it won't work in ctrlp-funky even though it matches with the fold markers just fine inside vim search.

I'm thinking maybe ctrlp-funky is ignoring all the comments in the source code? If so, can you give some hints on how I can actually achieve this?

And how do you like this functionality? I really think this could be useful for a lot of vim users, that I'd like to bring it to ctrlp-funky.

**Comment by timfeirg** [comment]
RFC @tacahiroy

**Comment by tacahiroy** [comment]
just didn't have time to look at. I'll check it soon--

Takahiro Yoshihara
tacahiroy@gmail

**Comment by tacahiroy** [comment]
yeah, that functionality may be useful for some ppl, dunno how many users want it though.

ctrlp-funky doesn't ignore any lines in the file, but it just parses the file to try to find lines that matched regexps.
I've tried the pattern you commented and it worked as expected:
![2018-07-16 12 20 32](https://user-images.githubusercontent.com/76614/42742062-c070df52-88f2-11e8-8567-ec1752360712.png)

And probably like this pattern should be supported:
```vim
if has('pythonx') "{{{
```

**Comment by timfeirg** [comment]
It didn't work at my first several attempts, but I just tried changing `autoload/ctrlp/funky/ft/vim.vim` to this and it indeed works as expected:

```vimL
function! ctrlp#funky#ft#vim#filters()
  let filters = [
        \ { 'pattern': '\m\C^[\t ]*fu\(n\|nc\|nct\|ncti\|nctio\|nction\)\?!\?[\t ]\+\S\+',
        \   'formatter': ['\m\C^[\t ]\+', '', ''] },
        \ { 'pattern': '^[\t ]*"[\t ]*.\+{',
        \   'formatter': [] }
  \ ]
  return filters
endfunction
```

Come to think of it, this feature does rely on some very specific foldmarker settings (although I think it's actually popular), probably not very useful and could potentially be harmful for some users.

Thus I'll just leave this snippet here and close this issue.
