### ISSUE TITLE
add pattern for vim9

### ISSUE THREAD

**Issue by Shane-XB-Qian** [tacahiroy/ctrlp-funky#127]
would you mind adding filter pattern for vim9?
- `def` and `export def`

// there would may have 'class' also, but for now, those two.

**Comment by tacahiroy** [comment]
yeah, that would be useful. will work on it.

**Comment by Shane-XB-Qian** [comment]
i saw you had upd the pattern, time to merge now? :-)
// so far perhaps just `export def` and `def`, i guess a quite long time would not have `export class` (or not necessary), so perhaps should be ok for now..

**Comment by tacahiroy** [comment]
Thanks for notifying this. I seemed to forget to merge my changes :p

**Comment by Shane-XB-Qian** [comment]
thx. and actually looks there would be new 'interface' keyword etc... too... not sure what's the end or too much, but so far perhaps ok. thx.
