### ISSUE TITLE
sort by MRU breaks navigation

### ISSUE THREAD

**Issue by timfeirg** [tacahiroy/ctrlp-funky#59]
I'm using 8e28397beb88c5cf3aad695996546fc3f326bea6, if I do this:

```
let g:ctrlp_funky_sort_by_mru = 1
```

I'll get this error when I try to navigate to function:

```
Error detected while processing function <SNR>114_AcceptSelection..ctrlp#funky#accept:
line   13:
E121: Undefined variable: bufnr
E116: Invalid arguments for function 238
```

___

looks like https://github.com/tacahiroy/ctrlp-funky/issues/8 is reappearing

**Comment by tacahiroy** [comment]
Fixed.
Thanks for reporting the issue.
