### ISSUE TITLE
messy code appears in input field when using ctrlp-funky in php files

### ISSUE THREAD

**Issue by lovelock** [tacahiroy/ctrlp-funky#63]
messy code appears in input field when using ctrlp-funky in php files. After deleting the messy code, I can use the function correctly.
![qq 20150302183458](https://cloud.githubusercontent.com/assets/2208731/6439148/dfd65420-c10a-11e4-9c4c-2fbf226357f3.png)

I've tested severval php files, the error repeats. For C++ and .vimrc, everything is OK.

**Comment by tacahiroy** [comment]
That kind of code isn't included Funky itself and I don't reproduce the issue.
Can you give me a sample file and minimal vimrc?
