### ISSUE TITLE
CSS support

### ISSUE THREAD

**Issue by anstosa** [tacahiroy/ctrlp-funky#69]
SublimeText's fuzzy function definition matching would match selectors in CSS files.

Can similar functionality be added here?

**Comment by tacahiroy** [comment]
I've just pushed very basic CSS support, it detects just IDs and classes for now though.
I don't think it has enough functionality for CSS, so your thoughts are appreciated at any time.

**Comment by anstosa** [comment]
Opened a pull request for some improvements, sorry I didn't just do that in the first place! :stuck_out_tongue:
