### ISSUE TITLE
Support for Perl Moose and Method::Signatures

### ISSUE THREAD

**Issue by imran-uk** [tacahiroy/ctrlp-funky#73]
Both of these are modern Perl things, eg.

`method _format_response($response) {`

    enum 'Foo::Types' , [qw(
        CH CN CU CY
    )];

    subtype FooType,
        as Str,
        where {
            my $type = $_;
            grep {/^$type$/} qw( organic mechanical alien )
        },
        message { "[$_] is not a valid Foo type" };

    coerce FooFields,
        from Undef,
        via { [] };

**Comment by tacahiroy** [comment]
In that case, do you expect `method _format_response($response)` and `Foo::Types` listed in CtrlP buffer?

**Comment by imran-uk** [comment]
Just do what CtrlP does now with normal subs, eg.

```sub _log_search_response { 	#:<buffer>:<line number>```

So in the case of a method, show the whole line:

```method _format_response($response) #:2:203```

and for Moose:

```enum 'Foo::Types' , [qw(   #4:20```

for subtype, show the first two lines:

    subtype FooType,
        as Str,

same for coerce

    coerce FooFields,
        from Undef,

Arigato!

**Comment by tacahiroy** [comment]
Understood. OK - will add those patterns for perl sometime soon.
Arigato for your advice.



2015年6月23日 0:08、0:08、Imran Chaudhry <notifications@github.com> のメッセージ:

**Comment by imran-uk** [comment]
Your welcome Takahiro-san.

Can I ask one unrelated question: is it possible to enable ctrlp-funky
automatically when I open a file? Right now I have to manually type in
:CtrlPFunky for it to appear in the CtrlP buffer.

On 22 June 2015 at 17:36, Takahiro Yoshihara <notifications@github.com>
wrote:

> Understood. OK - will add those patterns for perl sometime soon.
> Arigato for your advice.
>
>
>
> 2015年6月23日 0:08、0:08、Imran Chaudhry <notifications@github.com> のメッセージ:
> >Just do what CtrlP does now with normal subs, eg.
> >
> >```sub _log_search_response { #:<buffer>:<line number>```
> >
> >So in the case of a method, show the whole line:
> >
> >```method _format_response($response) #:2:203```
> >
> >and for Moose:
> >
> >```enum 'Foo::Types' , [qw( #4:20```
> >
> >for subtype, show the first two lines:
> >
> > subtype FooType,
> > as Str,
> >
> >same for coerce
> >
> > coerce FooFields,
> > from Undef,
> >
> >Arigato!
> >
> >---
> >Reply to this email directly or view it on GitHub:
> >https://github.com/tacahiroy/ctrlp-funky/issues/73#issuecomment-114145204
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tacahiroy/ctrlp-funky/issues/73#issuecomment-114173335>
> .
>



-- 
Key fingerprint = EF78 310C C517 9564 9ECA  82F6 68FA E621 17E1 5D16
http://about.me/imranchaudhry

**Comment by tacahiroy** [comment]
@imran-uk I've pushed changes for this finally. It would be great if you can confirm this is ok.
