### ISSUE TITLE
Weird behaviour after upgrade

### ISSUE THREAD

**Issue by craigp** [tacahiroy/ctrlp-funky#76]
Ever since I upgraded the other day I get two listings in the CtrlP window for each function and it's also finding function calls rather than function declarations (in JS).

Is there some new config I need or anything like that? 

Thanks for the great plugin, makes my day bearable.

**Comment by tacahiroy** [comment]
I guess both of things are unexpected behaviour, so they're bugs.
I'll investigate them asap.

Thanks for your report.
