### ISSUE TITLE
Breaking since last update

### ISSUE THREAD

**Issue by cj** [tacahiroy/ctrlp-funky#77]
Afternoon.  Since I updated to the version 3 days ago I'm getting this error:

```
Error detected while processing function ctrlp#funky#funky..ctrlp#init..ctrlp#setlines..ctrlp#funky#init..ctrlp#funky#candidates..ctrlp#funky#extract:
line   67:
E117: Unknown function: uniq
E15: Invalid expression: uniq(prior + sorted)
Press ENTER or type command to continue
```

**Comment by cj** [comment]
reverting to this commit `b5fd837e38a0688ba593bb17dbc7857a71763a84` fixes the issue.  Here's the line causing the issue:  https://github.com/tacahiroy/ctrlp-funky/commit/540afd365ace8b3351f4ff7479e98d9e133bbcb6#diff-a68387e6ef3a49b100a35da6c3a84777R337

**Comment by tacahiroy** [comment]
Thanks for reporting the issue.
