### ISSUE TITLE
Funky finds matches in the whole line

### ISSUE THREAD

**Issue by maxless** [tacahiroy/ctrlp-funky#78]
Is there a way to disable this using only function name?

**Comment by tacahiroy** [comment]
It depends on filetype. What filetype(s) are you working with?
Currently, ruby, php and go support like that option.

See g:ctrlp_funky_ruby_requires for example.

**Comment by tacahiroy** [comment]
ah - I didn't see the title of this issue.
It depends on filetype, most of filetype filters contain statements and / or arguments such as "function", "def" etc. though.

**Comment by maxless** [comment]
Well, I tested it on php filetype. The word "function" and all function parameters are matched. I'd really like to use only the function name since additional text interferes with the matching.

**Comment by tacahiroy** [comment]
I could imagine what you're thinking.
ok - I'll add like that feature for some filetypes that uses a keyword to define functions such as "function", "def" etc.

**Comment by maxless** [comment]
It would be great if you'd make an option for that. Can you also remove the function arguments? They are matched too.

**Comment by tacahiroy** [comment]
yeah - i thought the same thing as well. will do for PHP first

**Comment by tacahiroy** [comment]
@maxless I've implemented the feature into a branch `stripper-mode`.
Can you test the behaviour with this branch?
It supports only php for now, so pls add following config to your .vimrc:
```vim
let g:ctrlp_funky_strippers = [ 'php' ]
```

**Comment by maxless** [comment]
I've tried it and it works great so far. Thanks! I'll will use it in the
next few days.

2015-11-18 20:36 GMT+04:00 Takahiro Yoshihara <notifications@github.com>:

**Comment by tacahiroy** [comment]
Thanks for your checks.

FYI: I've just force pushed changes to the branch, so you need to change the variable name to `g:ctrlp_funky_nudists` if you use the latest code.
Though I've done some tests by myself, I'll merge the branch into master this weekend if there is no issues.

**Comment by maxless** [comment]
Thanks, I pulled the latest changes.

**Comment by tacahiroy** [comment]
merged the branch to master yesterday.
