### ISSUE TITLE
javascript  es6  problems 

### ISSUE THREAD

**Issue by holybreath** [tacahiroy/ctrlp-funky#83]
Sorry for only text description, because I never upload image successfully.

> function getSquare(x1,x2,y1,y2) {
>   ....
> }
> class MainStore {
>    constructor() {
>     ...
>   };
>   setPlace() {
> ...
> }

It seems in such a js module , the function names will duplicate twice.
if the file only has one grammar, with or without `function`, then the list will be fine.

**And the function list has a limit amount, is it possible to show all functions?**

Thanks!

**Comment by holybreath** [comment]
for more accuracy, `function getSquare(x1,x2,y1,y2) `  and `for `loop in it will be duplicated.

And I found the limit result config, `let g:ctrlp_match_window = 'results:50' " overcome limit imposed by max height
`

**Comment by tacahiroy** [comment]
Can you give me a sample file having the problem please?
Coz I don't reproduce duplication problem, I've reproduced the issue that `for` loop in the result though.

**Comment by holybreath** [comment]
sure, it seems I still can't upload any files, so I make a minimal sample below. if necessary please give me your email and I will send my screen shot and .js  to you.

> 'use strict';
function getimg64(img) {
}
function getRandomElement(arr) {
  return arr[Math.floor(Math.random()*arr.length)];
}
class MainStore {
  constructor() {
      };
  setPlaceVisible(place){
      }
  goToPlace(place) {   
  }
}
module.exports = MainStore;
