### ISSUE TITLE
Potential conflict with airblade/vim-gitgutter

### ISSUE THREAD

**Issue by yamsu** [tacahiroy/ctrlp-funky#85]
Ctrlp-funky is a lifesaver! Great plugin really help with large code files. However, recently I installed vim-gitgutter and ctrlp-funky has stopped working. Irrespective of the file type Ctrlp-funky shows -- No Entries --

If i comment out the vim-gitgutter, ctrlp-funky works fine

**Comment by tacahiroy** [comment]
Nice found! I've reproduced the issue. will investigate it.

**Comment by blinskey** [comment]
I'm having this problem as well and ran git-bisect on the gitgutter code, testing with Vim 8.0, patches 1-122. In the process, I discovered that ctrlp-funky actually sometimes works. If you run `:CtrlPFunky` multiple times in succession, it occasionally properly displays a list of functions. That would seem to point to a race condition.

The first bad commit in gitgutter appears to be 72d1005. And sure enough, it involves some sort of asynchronous operation.

I'm not a Vimscript expert, but I'd be happy to look into this when I have some time if no one else gets to it first.

**Comment by blinskey** [comment]
OK, I have a workaround and a vague idea of what's happening here. In `ctrlp#funky#init()`, the plugin switches buffers, gets a list of candidates, and switches back to the former buffer. This buffer switch kicks off an asynchronous process in GitGutter, which creates a race condition between the two plugins.

Unfortunately, I haven't been able to figure out exactly what GitGutter is doing here, but it might be obvious to someone fluent in Vimscript. What I do know is that the problem goes away if you slow down ctrlp-funky by inserting a call to `insert()` within `ctrlp#funky#init()` anywhere after `bufwinnr()` is executed and before `ctrlp#funky#candidates()` is called.

The good news is that this problem goes away if you just disable async in GitGutter by adding the following line to your .vimrc: 

     let g:gitgutter_async = 1

I may look into this further if I get a chance, but in the meantime, if anyone else wants to dig into this, I'd welcome their help.

**Comment by tracyone** [comment]
my solution:

```vim
"handle bug of gitgutter
function! s:ctrlp_funky()
    let g:gitgutter_async=0
    :CtrlPFunky
    let g:gitgutter_async=1
endfunction
nnoremap <c-k> :call <SID>ctrlp_funky()<cr>
```

**Comment by yamsu** [comment]
@tacahiroy Works like a charm!! 
Just wanted to add a little to the same, so you can find function under the cursor, which I use often. Of course it only works if the function is in the same file.

"handle bug of gitgutter
function! s:ctrlp_funky(item)
	if a:item != ''
		let g:gitgutter_async=0
		execute 'CtrlPFunky' a:item
		let g:gitgutter_async=1
	else
		let g:gitgutter_async=0
		:CtrlPFunky
		let g:gitgutter_async=1
	endif
endfunction
nnoremap <Leader>ff :call <SID>ctrlp_funky('')<cr>
nnoremap <Leader>fF :execute 'call <SID>ctrlp_funky("'.expand('<cword>').'")'<Cr>
